-- Disable foreign key checks temporarily to allow dropping tables in any order
SET session_replication_role = 'replica';

-- Drop fantasy schema if it exists (ensures a clean slate for schema creation)
DROP SCHEMA IF EXISTS fantasy CASCADE;

-- Drop the update_timestamp function if it exists (will be recreated in this file)
-- DROP FUNCTION IF EXISTS update_timestamp();

-- Re-enable foreign key checks
SET session_replication_role = 'origin';

-- Create necessary extensions if they don't exist (for UUID generation)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Function to update the 'updated_at' column
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


--- Function to exceute the draft
CREATE OR REPLACE FUNCTION call_run_draft_on_status_complete()
RETURNS TRIGGER AS $$
DECLARE
  payload jsonb;
BEGIN
  -- Check the condition before proceeding
  IF NEW.status = 'complete' THEN
    -- Build the JSON payload with data from the new row.
    payload := jsonb_build_object(
      'leagueId', NEW.league_id,
      'season', NEW.season_year,
      'currentWeek', 0
    );

    -- Perform the HTTP POST request.
   PERFORM net.http_post(
     url := 'http://host.docker.internal:54321/functions/v1/run-draft'::text,
     body := payload::jsonb,
     headers := '{"Content-Type": "application/json"}'::jsonb,
     timeout_milliseconds := 10000
   );

  END IF;

  -- Return the row to finish the trigger.
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- sets up a helper function create a public key function
CREATE OR REPLACE FUNCTION generate_key()
RETURNS TEXT AS $$
DECLARE
    alphabet TEXT := '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    timestamp_num BIGINT;
    key_str TEXT := '';
    random_num BIGINT;
BEGIN
    -- Get the current timestamp as a number of milliseconds since the epoch
    timestamp_num := EXTRACT(EPOCH FROM NOW()) * 1000;
    
    -- Convert the timestamp to a base62 string
    WHILE timestamp_num > 0 LOOP
        key_str := SUBSTR(alphabet, (timestamp_num % 62)::INTEGER + 1, 1) || key_str;
        timestamp_num := timestamp_num / 62;
    END LOOP;
    
    -- Get a random number and convert it to base62
    random_num := (random() * 62 * 62)::BIGINT;
    WHILE random_num > 0 LOOP
        key_str := SUBSTR(alphabet, (random_num % 62)::INTEGER + 1, 1) || key_str;
        random_num := random_num / 62;
    END LOOP;
    
    -- Truncate the key to 5 characters and return it
    RETURN SUBSTRING(key_str, 1, 5);
END;
$$ LANGUAGE plpgsql;
---

-- --- FANTASY SCHEMA TABLES ---

-- Create fantasy schema
CREATE SCHEMA IF NOT EXISTS fantasy;

DROP TABLE IF EXISTS users CASCADE;
-- Table for Users (Auth UUID in this table only, user_id for internal references)
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255),
    team_name VARCHAR(255),
    team_description TEXT,
    logo_url VARCHAR (255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Leagues (commissioner_user_id links to users.user_id)
DROP TABLE IF EXISTS leagues CASCADE;
CREATE TABLE leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    commissioner_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    league_options jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_leagues
BEFORE UPDATE ON leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for User-League Relationships (many-to-many) (Now uses user_id)
DROP TABLE IF EXISTS user_leagues CASCADE;
CREATE TABLE user_leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    league_id INTEGER NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    role VARCHAR(255) DEFAULT 'member',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_user_league UNIQUE (user_id, league_id),
    CONSTRAINT fk_user_leagues_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_leagues_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_leagues
BEFORE UPDATE ON user_leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for NFL Teams
DROP TABLE IF EXISTS nfl_teams CASCADE;
CREATE TABLE nfl_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    abbreviation VARCHAR(255) NOT NULL,
    nfl_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table for NFL Players
DROP TABLE IF EXISTS nfl_players CASCADE;
CREATE TABLE nfl_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    nfl_id VARCHAR(255) UNIQUE,
    nfl_team_id INTEGER REFERENCES nfl_teams(id) ON DELETE SET NULL,
    position_type VARCHAR(255),
    source varchar(255) default 'genius',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_players
BEFORE UPDATE ON nfl_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


CREATE TRIGGER set_updated_at_nfl_teams
BEFORE UPDATE ON nfl_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- NFL GAMES SCHEDULE PER WEEK 
CREATE TABLE nfl_games (

    game_week_id integer REFERENCES game_weeks(id) ON DELETE SET NULL,
    nfl_id integer, 
    name varchar(255),
    home_team_id integer REFERENCES nfl_teams(id) ON DELETE SET NULL,
    away_team_id integer REFERENCES nfl_teams(id) ON DELETE SET NULL,
    venue varchar(255),
    start_date timestamp with time zone,
    modified_on timestamp with time zone,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_games
BEFORE UPDATE ON nfl_games
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
---

-- Table for NFL Player Types
CREATE TABLE nfl_player_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_player_types
BEFORE UPDATE ON nfl_player_types
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for User Roster (Now uses user_id)
DROP TABLE IF EXISTS user_roster CASCADE;
CREATE TABLE user_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    nfl_player_id INTEGER NOT NULL,
    team_name VARCHAR(255),
    season_year INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_user_roster_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
     -- New foreign key constraint to nfl_players
    CONSTRAINT fk_user_roster_nfl_player FOREIGN KEY (nfl_player_id) REFERENCES nfl_players(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_roster
BEFORE UPDATE ON user_roster
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table For Game Weeks
DROP TABLE IF EXISTS game_weeks CASCADE;
CREATE TABLE game_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER,
    season_year INTEGER,
    nfl_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_game_weeks
BEFORE UPDATE ON game_weeks
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- SET UP FOR GAME WEEK LEAGUES 
DROP TABLE IF EXISTS game_week_leagues CASCADE;
CREATE TABLE game_week_leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id INTEGER NOT NULL DEFAULT 1,
    game_week_id INTEGER,
    mod_assignments JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_game_week_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE
);

CREATE INDEX index_game_week_leagues_on_league_id ON game_week_leagues (league_id);

CREATE TRIGGER set_updated_at_game_week_leagues
BEFORE UPDATE ON game_week_leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- ALTER TABLE  start at league level -> week level -> matchup level -> player level
-- 
-- LEAGUE SETTINGS 
-- GAME WEEK MATCHUP
-- GAME WEEK TEAM PLAYERS
ALTER TABLE game_week_teams
ADD column mod_assignments JSONB;

ALTER TABLE league_settings
ADD column mod_assignments JSONB DEFAULT '{"K": [], "QB": [], "RB": [], "WR": [], "ALL": [1], "DEF": []}'::jsonb;

ALTER TABLE game_week_matchups
RENAME column mode_assignments TO mod_assignments;

ALTER TABLE game_week_team_players
add COLUMN mod_assignment_id BIGINT;

-- Table for Game Week Teams (Now uses user_id)
DROP TABLE IF EXISTS game_week_teams CASCADE;
CREATE TABLE game_week_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    league_id INTEGER NOT NULL DEFAULT 1,
    game_week_id INTEGER,
    mod_assignments JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_game_week_teams_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_teams_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE INDEX index_game_week_teams_on_league_id ON game_week_teams (league_id);
CREATE INDEX index_game_week_teams_on_user_id ON game_week_teams (user_id);

CREATE TRIGGER set_updated_at_game_week_teams
BEFORE UPDATE ON game_week_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();




-- Table for Game Week Team Players
DROP TABLE IF EXISTS game_week_team_players CASCADE;
CREATE TABLE game_week_team_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_team_id INTEGER REFERENCES game_week_teams(id) ON DELETE CASCADE,
    nfl_player_id INTEGER,
    playing BOOLEAN,
    roster_slot VARCHAR(255),
    mod_assignments JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_player_gameweek_team UNIQUE (game_week_team_id, nfl_player_id)
);

CREATE INDEX index_game_week_team_players_on_game_week_team_id ON game_week_team_players (game_week_team_id);
CREATE INDEX index_game_week_team_players_on_nfl_player_id ON game_week_team_players (nfl_player_id);

CREATE TRIGGER set_updated_at_game_week_team_players
BEFORE UPDATE ON game_week_team_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Matchups
DROP TABLE IF EXISTS game_week_matchups CASCADE;
CREATE TABLE game_week_matchups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_id INTEGER NOT NULL REFERENCES game_weeks(id) ON DELETE CASCADE,
    home_game_week_team_ids INTEGER[] NOT NULL DEFAULT '{}',
    away_game_week_team_ids INTEGER[] NOT NULL DEFAULT '{}',
    home_team_score NUMERIC(8,2) DEFAULT 0.00,
    away_team_score NUMERIC(8,2) DEFAULT 0.00,
    mod_assignments JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_gameweek_home_away_team UNIQUE (game_week_id, home_game_week_team_id, away_game_week_team_id),
    CONSTRAINT check_different_teams CHECK (home_game_week_team_id <> away_game_week_team_id)
);

CREATE INDEX index_game_week_matchups_on_game_week_id ON game_week_matchups (game_week_id);
CREATE INDEX index_game_week_matchups_on_home_game_week_team_id ON game_week_matchups (home_game_week_team_id);
CREATE INDEX index_game_week_matchups_on_away_game_week_team_id ON game_week_matchups (away_game_week_team_id);

CREATE TRIGGER set_updated_at_game_week_matchups
BEFORE UPDATE ON game_week_matchups
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Match Players
DROP TABLE IF EXISTS match_players CASCADE;
CREATE TABLE match_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passing_yards INTEGER DEFAULT 0,
    passing_tds INTEGER DEFAULT 0,
    passing_twoptm INTEGER DEFAULT 0,
    interceptions_thrown INTEGER DEFAULT 0,
    rushing_yards INTEGER DEFAULT 0,
    rushing_tds INTEGER DEFAULT 0,
    rushing_twoptm INTEGER DEFAULT 0,
    receiving_receptions INTEGER DEFAULT 0,
    receiving_yards INTEGER DEFAULT 0,
    receiving_tds INTEGER DEFAULT 0,
    receiving_twoptm INTEGER DEFAULT 0,
    times_sacked INTEGER DEFAULT 0,
    fumbles_lost INTEGER DEFAULT 0,
    touch_carries INTEGER DEFAULT 0,
    touch_receptions INTEGER DEFAULT 0,
    touches INTEGER DEFAULT 0,
    targets_receptions INTEGER DEFAULT 0,
    targets INTEGER DEFAULT 0,
    reception_percentage NUMERIC(5,2) DEFAULT 0.00,
    rz_target INTEGER DEFAULT 0,
    rz_touch INTEGER DEFAULT 0,
    rz_g2g INTEGER DEFAULT 0,
    pat_made INTEGER DEFAULT 0,
    pat_missed INTEGER DEFAULT 0,
    fg_made_0_19 INTEGER DEFAULT 0,
    fg_made_20_29 INTEGER DEFAULT 0,
    fg_made_30_39 INTEGER DEFAULT 0,
    fg_made_40_49 INTEGER DEFAULT 0,
    fg_made_50_plus INTEGER DEFAULT 0,
    fg_miss_0_19 INTEGER DEFAULT 0,
    fg_miss_20_29 INTEGER DEFAULT 0,
    fg_miss_30_39 INTEGER DEFAULT 0,
    tackles_total INTEGER DEFAULT 0,
    tackles_assisted INTEGER DEFAULT 0,
    sacks_made NUMERIC(8,2) DEFAULT 0.00,
    tackles_for_loss INTEGER DEFAULT 0,
    forced_fumbles INTEGER DEFAULT 0,
    fumbles_won INTEGER DEFAULT 0,
    interceptions_caught INTEGER DEFAULT 0,
    safeties INTEGER DEFAULT 0,
    defensive_two_pt_returns INTEGER DEFAULT 0,
    blocked_kicks INTEGER DEFAULT 0,
    passes_defended INTEGER DEFAULT 0,
    qb_hits INTEGER DEFAULT 0,
    interception_return_yards INTEGER DEFAULT 0,
    fumble_return_yards INTEGER DEFAULT 0,
    defense_touchdowns INTEGER DEFAULT 0,
    points_conceded NUMERIC(8,2) DEFAULT 0.00,
    points NUMERIC(8,2) DEFAULT 0.00,
    game_week_id INTEGER REFERENCES game_weeks(id) ON DELETE CASCADE,
    nfl_player_id INTEGER REFERENCES nfl_players(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_player_gameweek UNIQUE (game_week_id, nfl_player_id)
);

CREATE TRIGGER set_updated_at_match_players
BEFORE UPDATE ON match_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();



-- Position ENUM Type
DROP TYPE IF EXISTS positions;
CREATE TYPE positions AS ENUM ('ALL', 'QB', 'RB', 'WR', 'TE', 'K', 'DEF', 'FLEX');

-- Table for MODES
-- modes table
-- name
-- scoring type [traditional, KOTH, position battle]
-- available mods ?
-- mods per week ?
-- mod week assignment ?

DROP TABLE IF EXISTS modes CASCADE;
CREATE TABLE modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    scoring_type VARCHAR(255) NOT NULL DEFAULT 'traditional',
    available_mods JSONB NOT NULL DEFAULT '{}'::jsonb,
    mods_per_week  JSONB NOT NULL DEFAULT '{}'::jsonb,
    defaultmod_week_assignment JSONB NOT NULL DEFAULT '{"K": [], "QB": [], "RB": [], "WR": [], "ALL": [1], "DEF": []}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_modes
BEFORE UPDATE ON modes
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for Mods
DROP TABLE IF EXISTS mods CASCADE;
CREATE TABLE mods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    passing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_thrown_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receptions_multiplier NUMERIC(5,2) DEFAULT 0.00,
    two_pt_conversion_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_lost_multiplier NUMERIC(5,2) DEFAULT 0.00,
    times_sacked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_kicked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_missed_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_0_19_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_20_29_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_30_39_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_40_49_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_50_plus_multiplier NUMERIC(5,2) DEFAULT 0.00,
    sacks_made_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defense_touchdowns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_won_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_caught_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_total_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_assisted_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_for_loss_multiplier NUMERIC(5,2) DEFAULT 0.00,
    forced_fumbles_multiplier NUMERIC(5,2) DEFAULT 0.00,
    safeties_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defensive_two_pt_returns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    blocked_kicks_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passes_defended_multiplier NUMERIC(5,2) DEFAULT 0.00,
    qb_hits_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interception_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumble_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    position_affected positions[] DEFAULT ARRAY['ALL']::positions[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_mods
BEFORE UPDATE ON mods
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for League Settings
DROP TABLE IF EXISTS league_settings CASCADE;
CREATE TABLE league_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id INTEGER UNIQUE NOT NULL,
    total_roster_size INTEGER NOT NULL DEFAULT 16,
    starting_lineup_size INTEGER NOT NULL DEFAULT 9,
    bench_size INTEGER NOT NULL DEFAULT 7,
    starting_position_requirements JSONB NOT NULL DEFAULT '{}'::jsonb,
    mode_id INTEGER NOT NULL DEFAULT 1,
    draft_type VARCHAR(255) NOT NULL DEFAULT 'Snake',
    draft_order_reversed_after_round BOOLEAN NOT NULL DEFAULT TRUE,
    picks_per_round INTEGER NOT NULL DEFAULT 1,
    draft_start_date TIMESTAMP WITH TIME ZONE,
    draft_end_date TIMESTAMP WITH TIME ZONE,
    waiver_type VARCHAR(255) NOT NULL DEFAULT 'FAAB',
    faab_budget INTEGER NOT NULL DEFAULT 100,
    waiver_run_day VARCHAR(255) DEFAULT 'Wednesday',
    waiver_run_time TIME WITH TIME ZONE DEFAULT '03:00:00-07',
    allow_trades BOOLEAN NOT NULL DEFAULT TRUE,
    trade_deadline TIMESTAMP WITH TIME ZONE,
    trade_review_period_hours INTEGER DEFAULT 24,
    playoff_start_week INTEGER,
    num_playoff_teams INTEGER,
    championship_week INTEGER,
    broadcast_channel VARCHAR(5) UNIQUE NOT NULL DEFAULT generate_key(),
    league_status VARCHAR(255) NOT NULL DEFAULT 'Drafting',
    mod_assignments JSONB DEFAULT '{"K": [], "QB": [], "RB": [], "WR": [], "ALL": [1], "DEF": []}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_league_settings_league
        FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_league_settings_mode
        FOREIGN KEY (mode_id) REFERENCES modes(id) ON DELETE RESTRICT
);

CREATE INDEX index_league_settings_on_league_id ON league_settings (league_id);
CREATE INDEX index_league_settings_on_mode_id ON league_settings (mode_id);

CREATE TRIGGER set_updated_at_league_settings
BEFORE UPDATE ON league_settings
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();



-- Table for League Drafts
DROP TABLE IF EXISTS draft_picks CASCADE;
CREATE TABLE draft_picks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL,
    season_year INTEGER NOT NULL,
    user_id BIGINT,
    nfl_player_id BIGINT,
    round_number INTEGER NOT NULL,
    pick_number INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Foreign key constraints
    CONSTRAINT fk_draft_picks_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_picks_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT fk_draft_picks_nfl_player FOREIGN KEY (nfl_player_id) REFERENCES nfl_players(id) ON DELETE SET NULL,
    
    -- Uniqueness constraint for each pick within a league
    CONSTRAINT unique_league_pick_number UNIQUE (league_id, pick_number),
    
    -- Check constraint to ensure status is a valid value
    CONSTRAINT check_draft_pick_status CHECK (status IN ('pending', 'active', 'complete'))
);

-- Index for faster lookups on league and pick number
CREATE INDEX index_draft_picks_on_league_id ON draft_picks (league_id);
CREATE INDEX index_draft_picks_on_user_id ON draft_picks (user_id);
CREATE INDEX index_draft_picks_on_nfl_player_id ON draft_picks (nfl_player_id);
CREATE INDEX index_draft_picks_on_status ON draft_picks (status);

-- Trigger to automatically update the updated_at timestamp on row modification
CREATE TRIGGER set_updated_at_draft_picks
BEFORE UPDATE ON draft_picks
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
--
-- The trigger now executes runs the draft when the status is set to 'complete'
CREATE TRIGGER draft_pick_on_status_update
AFTER UPDATE ON draft_picks
FOR EACH ROW EXECUTE FUNCTION call_run_draft_on_status_complete();

---
-- New Table for Matchup to Mode Assignments
DROP TABLE IF EXISTS matchup_mode_assignments CASCADE;
-- CREATE TABLE matchup_mode_assignments (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     game_week_matchup_id BIGINT NOT NULL REFERENCES game_week_matchups(id) ON DELETE CASCADE,
--     mode_id BIGINT NOT NULL REFERENCES modes(id) ON DELETE RESTRICT,
--     position_type VARCHAR(255) NOT NULL, -- 'ALL' or a specific position like 'QB', 'RB', 'WR'
--     mode_assignments JSONB DEFAULT '{"K": [], "QB": [], "RB": [], "WR": [], "ALL": [1], "DEF": []}'::jsonb,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--     CONSTRAINT unique_matchup_mode_position UNIQUE (game_week_matchup_id, mode_id, position_type)
-- );

-- Index for faster lookups
CREATE INDEX index_matchup_mode_assignments_on_matchup_id ON matchup_mode_assignments (game_week_matchup_id);
CREATE INDEX index_matchup_mode_assignments_on_mode_id ON matchup_mode_assignments (mode_id);
CREATE INDEX index_matchup_mode_assignments_on_position_type ON matchup_mode_assignments (position_type);

-- Trigger to automatically update the updated_at timestamp on row modification
CREATE TRIGGER set_updated_at_matchup_mode_assignments
BEFORE UPDATE ON matchup_mode_assignments
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
---

GRANT USAGE ON SCHEMA fantasy TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA fantasy TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA fantasy TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA fantasy TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA fantasy GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA fantasy GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA fantasy GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

