-- Disable foreign key checks temporarily to allow dropping tables in any order
SET session_replication_role = 'replica';

-- Drop realtime schema if it exists (ensures a clean slate for schema creation)
DROP SCHEMA IF EXISTS realtime CASCADE;

-- Re-enable foreign key checks
SET session_replication_role = 'origin';

-- --- REALTIME SCHEMA TABLES ---

-- Create the realtime schema
CREATE SCHEMA IF NOT EXISTS realtime;

-- Table for Realtime Topics
CREATE TABLE realtime.topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    league_id INTEGER REFERENCES fantasy.leagues(id) ON DELETE CASCADE, -- Link to a specific league, can be NULL for global topics
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: The update_timestamp function is assumed to be created in fantasy_schema.sql
CREATE TRIGGER set_updated_at_realtime_topics
BEFORE UPDATE ON realtime.topics
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for Realtime Messages (Now uses sender_user_id)
CREATE TABLE realtime.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(255) NOT NULL REFERENCES realtime.topics(name) ON UPDATE CASCADE,
    sender_user_id BIGINT NOT NULL REFERENCES fantasy.users(user_id) ON DELETE CASCADE, -- Links to fantasy.users.user_id
    content TEXT NOT NULL,
    extension VARCHAR(255) DEFAULT 'message',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: The update_timestamp function is assumed to be created in fantasy_schema.sql
CREATE TRIGGER set_updated_at_realtime_messages
BEFORE UPDATE ON realtime.messages
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();