-- Disable foreign key checks temporarily to allow dropping tables in any order
SET session_replication_role = 'replica';

-- Drop fantasy schema if it exists (ensures a clean slate for schema creation)
DROP SCHEMA IF EXISTS fantasy CASCADE;

-- Drop the update_timestamp function if it exists (will be recreated in this file)
DROP FUNCTION IF EXISTS update_timestamp();

-- Re-enable foreign key checks
SET session_replication_role = 'origin';

-- Create necessary extensions if they don't exist (for UUID generation)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Function to update the 'updated_at' column
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- --- FANTASY SCHEMA TABLES ---

-- Create fantasy schema
CREATE SCHEMA IF NOT EXISTS fantasy;

DROP TABLE IF EXISTS fantasy.users CASCADE;
-- Table for Users (Auth UUID in this table only, user_id for internal references)
CREATE TABLE fantasy.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255),
    team_name VARCHAR(255),
    team_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_users
BEFORE UPDATE ON fantasy.users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Leagues (commissioner_user_id links to fantasy.users.user_id)
DROP TABLE IF EXISTS fantasy.leagues CASCADE;
CREATE TABLE fantasy.leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    commissioner_user_id BIGINT REFERENCES fantasy.users(user_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_leagues
BEFORE UPDATE ON fantasy.leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for User-League Relationships (many-to-many) (Now uses user_id)
DROP TABLE IF EXISTS fantasy.user_leagues CASCADE;
CREATE TABLE fantasy.user_leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    league_id INTEGER NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    role VARCHAR(255) DEFAULT 'member',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_user_league UNIQUE (user_id, league_id),
    CONSTRAINT fk_user_leagues_user FOREIGN KEY (user_id) REFERENCES fantasy.users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_leagues_league FOREIGN KEY (league_id) REFERENCES fantasy.leagues(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_leagues
BEFORE UPDATE ON fantasy.user_leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for User Roster (Now uses user_id)
DROP TABLE IF EXISTS fantasy.user_roster CASCADE;
CREATE TABLE fantasy.user_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    nfl_player_id INTEGER NOT NULL,
    team_name VARCHAR(255),
    season_year INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_user_roster_user FOREIGN KEY (user_id) REFERENCES fantasy.users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_roster
BEFORE UPDATE ON fantasy.user_roster
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for NFL Teams
DROP TABLE IF EXISTS fantasy.nfl_teams CASCADE;
CREATE TABLE fantasy.nfl_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_teams
BEFORE UPDATE ON fantasy.nfl_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for NFL Player Types
CREATE TABLE fantasy.nfl_player_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_player_types
BEFORE UPDATE ON fantasy.nfl_player_types
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for NFL Players
DROP TABLE IF EXISTS fantasy.nfl_players CASCADE;
CREATE TABLE fantasy.nfl_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    nfl_id VARCHAR(255),
    nfl_team_id INTEGER REFERENCES fantasy.nfl_teams(id) ON DELETE SET NULL,
    position_type VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_players
BEFORE UPDATE ON fantasy.nfl_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table For Game Weeks
DROP TABLE IF EXISTS fantasy.game_weeks CASCADE;
CREATE TABLE fantasy.game_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER,
    season_year INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_game_weeks
BEFORE UPDATE ON fantasy.game_weeks
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Teams (Now uses user_id)
DROP TABLE IF EXISTS fantasy.game_week_teams CASCADE;
CREATE TABLE fantasy.game_week_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    league_id INTEGER NOT NULL DEFAULT 1,
    game_week_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_game_week_teams_league FOREIGN KEY (league_id) REFERENCES fantasy.leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_teams_user FOREIGN KEY (user_id) REFERENCES fantasy.users(user_id) ON DELETE SET NULL
);

CREATE INDEX index_game_week_teams_on_league_id ON fantasy.game_week_teams (league_id);
CREATE INDEX index_game_week_teams_on_user_id ON fantasy.game_week_teams (user_id);

CREATE TRIGGER set_updated_at_game_week_teams
BEFORE UPDATE ON fantasy.game_week_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Team Players
DROP TABLE IF EXISTS fantasy.game_week_team_players CASCADE;
CREATE TABLE fantasy.game_week_team_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_team_id INTEGER REFERENCES fantasy.game_week_teams(id) ON DELETE CASCADE,
    nfl_player_id INTEGER,
    playing BOOLEAN,
    roster_slot VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_player_gameweek_team UNIQUE (game_week_team_id, nfl_player_id)
);

CREATE INDEX index_game_week_team_players_on_game_week_team_id ON fantasy.game_week_team_players (game_week_team_id);
CREATE INDEX index_game_week_team_players_on_nfl_player_id ON fantasy.game_week_team_players (nfl_player_id);

CREATE TRIGGER set_updated_at_game_week_team_players
BEFORE UPDATE ON fantasy.game_week_team_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Matchups
DROP TABLE IF EXISTS fantasy.game_week_matchups CASCADE;
CREATE TABLE fantasy.game_week_matchups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_id INTEGER NOT NULL REFERENCES fantasy.game_weeks(id) ON DELETE CASCADE,
    home_game_week_team_id INTEGER NOT NULL REFERENCES fantasy.game_week_teams(id) ON DELETE CASCADE,
    away_game_week_team_id INTEGER NOT NULL REFERENCES fantasy.game_week_teams(id) ON DELETE CASCADE,
    home_team_score NUMERIC(8,2) DEFAULT 0.00,
    away_team_score NUMERIC(8,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_gameweek_home_away_team UNIQUE (game_week_id, home_game_week_team_id, away_game_week_team_id),
    CONSTRAINT check_different_teams CHECK (home_game_week_team_id <> away_game_week_team_id)
);

CREATE INDEX index_game_week_matchups_on_game_week_id ON fantasy.game_week_matchups (game_week_id);
CREATE INDEX index_game_week_matchups_on_home_game_week_team_id ON fantasy.game_week_matchups (home_game_week_team_id);
CREATE INDEX index_game_week_matchups_on_away_game_week_team_id ON fantasy.game_week_matchups (away_game_week_team_id);

CREATE TRIGGER set_updated_at_game_week_matchups
BEFORE UPDATE ON fantasy.game_week_matchups
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Match Players
DROP TABLE IF EXISTS fantasy.match_players CASCADE;
CREATE TABLE fantasy.match_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passing_yards INTEGER DEFAULT 0,
    passing_tds INTEGER DEFAULT 0,
    passing_twoptm INTEGER DEFAULT 0,
    interceptions_thrown INTEGER DEFAULT 0,
    rushing_yards INTEGER DEFAULT 0,
    rushing_tds INTEGER DEFAULT 0,
    rushing_twoptm INTEGER DEFAULT 0,
    receiving_receptions INTEGER DEFAULT 0,
    receiving_yards INTEGER DEFAULT 0,
    receiving_tds INTEGER DEFAULT 0,
    receiving_twoptm INTEGER DEFAULT 0,
    times_sacked INTEGER DEFAULT 0,
    fumbles_lost INTEGER DEFAULT 0,
    touch_carries INTEGER DEFAULT 0,
    touch_receptions INTEGER DEFAULT 0,
    touches INTEGER DEFAULT 0,
    targets_receptions INTEGER DEFAULT 0,
    targets INTEGER DEFAULT 0,
    reception_percentage NUMERIC(5,2) DEFAULT 0.00,
    rz_target INTEGER DEFAULT 0,
    rz_touch INTEGER DEFAULT 0,
    rz_g2g INTEGER DEFAULT 0,
    pat_made INTEGER DEFAULT 0,
    pat_missed INTEGER DEFAULT 0,
    fg_made_0_19 INTEGER DEFAULT 0,
    fg_made_20_29 INTEGER DEFAULT 0,
    fg_made_30_39 INTEGER DEFAULT 0,
    fg_made_40_49 INTEGER DEFAULT 0,
    fg_made_50_plus INTEGER DEFAULT 0,
    fg_miss_0_19 INTEGER DEFAULT 0,
    fg_miss_20_29 INTEGER DEFAULT 0,
    fg_miss_30_39 INTEGER DEFAULT 0,
    tackles_total INTEGER DEFAULT 0,
    tackles_assisted INTEGER DEFAULT 0,
    sacks_made NUMERIC(8,2) DEFAULT 0.00,
    tackles_for_loss INTEGER DEFAULT 0,
    forced_fumbles INTEGER DEFAULT 0,
    fumbles_won INTEGER DEFAULT 0,
    interceptions_caught INTEGER DEFAULT 0,
    safeties INTEGER DEFAULT 0,
    defensive_two_pt_returns INTEGER DEFAULT 0,
    blocked_kicks INTEGER DEFAULT 0,
    passes_defended INTEGER DEFAULT 0,
    qb_hits INTEGER DEFAULT 0,
    interception_return_yards INTEGER DEFAULT 0,
    fumble_return_yards INTEGER DEFAULT 0,
    defense_touchdowns INTEGER DEFAULT 0,
    points_conceded NUMERIC(8,2) DEFAULT 0.00,
    points NUMERIC(8,2) DEFAULT 0.00,
    game_week_id INTEGER REFERENCES fantasy.game_weeks(id) ON DELETE CASCADE,
    nfl_player_id INTEGER REFERENCES fantasy.nfl_players(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_player_gameweek UNIQUE (game_week_id, nfl_player_id)
);

CREATE TRIGGER set_updated_at_match_players
BEFORE UPDATE ON fantasy.match_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Modes
DROP TABLE IF EXISTS fantasy.modes CASCADE;
CREATE TABLE fantasy.modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    passing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_thrown_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receptions_multiplier NUMERIC(5,2) DEFAULT 0.00,
    two_pt_conversion_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_lost_multiplier NUMERIC(5,2) DEFAULT 0.00,
    times_sacked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_kicked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_missed_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_0_19_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_20_29_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_30_39_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_40_49_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_50_plus_multiplier NUMERIC(5,2) DEFAULT 0.00,
    sacks_made_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defense_touchdowns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_won_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_caught_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_total_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_assisted_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_for_loss_multiplier NUMERIC(5,2) DEFAULT 0.00,
    forced_fumbles_multiplier NUMERIC(5,2) DEFAULT 0.00,
    safeties_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defensive_two_pt_returns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    blocked_kicks_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passes_defended_multiplier NUMERIC(5,2) DEFAULT 0.00,
    qb_hits_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interception_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumble_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_modes
BEFORE UPDATE ON fantasy.modes
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for League Settings
DROP TABLE IF EXISTS fantasy.league_settings CASCADE;
CREATE TABLE fantasy.league_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id INTEGER UNIQUE NOT NULL,
    total_roster_size INTEGER NOT NULL DEFAULT 16,
    starting_lineup_size INTEGER NOT NULL DEFAULT 9,
    bench_size INTEGER NOT NULL DEFAULT 7,
    starting_position_requirements JSONB NOT NULL DEFAULT '{}'::jsonb,
    mode_id INTEGER NOT NULL DEFAULT 1,
    draft_type VARCHAR(255) NOT NULL DEFAULT 'Snake',
    draft_order_reversed_after_round BOOLEAN NOT NULL DEFAULT TRUE,
    picks_per_round INTEGER NOT NULL DEFAULT 1,
    draft_start_date TIMESTAMP WITH TIME ZONE,
    draft_end_date TIMESTAMP WITH TIME ZONE,
    waiver_type VARCHAR(255) NOT NULL DEFAULT 'FAAB',
    faab_budget INTEGER NOT NULL DEFAULT 100,
    waiver_run_day VARCHAR(255) DEFAULT 'Wednesday',
    waiver_run_time TIME WITH TIME ZONE DEFAULT '03:00:00-07',
    allow_trades BOOLEAN NOT NULL DEFAULT TRUE,
    trade_deadline TIMESTAMP WITH TIME ZONE,
    trade_review_period_hours INTEGER DEFAULT 24,
    playoff_start_week INTEGER,
    num_playoff_teams INTEGER,
    championship_week INTEGER,
    league_status VARCHAR(255) NOT NULL DEFAULT 'Drafting',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_league_settings_league
        FOREIGN KEY (league_id) REFERENCES fantasy.leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_league_settings_mode
        FOREIGN KEY (mode_id) REFERENCES fantasy.modes(id) ON DELETE RESTRICT
);

CREATE INDEX index_league_settings_on_league_id ON fantasy.league_settings (league_id);
CREATE INDEX index_league_settings_on_mode_id ON fantasy.league_settings (mode_id);

CREATE TRIGGER set_updated_at_league_settings
BEFORE UPDATE ON fantasy.league_settings
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();