-- Function to update the 'updated_at' column
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Table for Game Week Team Players
DROP TABLE IF EXISTS game_week_team_players CASCADE;

CREATE TABLE game_week_team_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_team_id INTEGER,
    nfl_player_id INTEGER,
    playing BOOLEAN,
    roster_slot VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Composite Unique Constraint
    CONSTRAINT unique_player_gameweek_team UNIQUE (game_week_team_id, nfl_player_id)
);

CREATE INDEX index_game_week_team_players_on_game_week_team_id ON game_week_team_players (game_week_team_id);
CREATE INDEX index_game_week_team_players_on_nfl_player_id ON game_week_team_players (nfl_player_id);

CREATE TRIGGER set_updated_at_game_week_team_players
BEFORE UPDATE ON game_week_team_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();



--Table for game week teams
DROP TABLE IF EXISTS game_week_teams CASCADE;

CREATE TABLE game_week_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    league_id INTEGER NOT NULL DEFAULT 1, -- Default to league ID 
    game_week_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ADD CONSTRAINT fk_game_week_teams_league
FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;

-- Add an index for league_id on game_week_teams for better query performance
CREATE INDEX index_game_week_teams_on_league_id ON game_week_teams (league_id);
CREATE INDEX index_game_week_teams_on_user_id ON game_week_teams (user_id);

CREATE TRIGGER set_updated_at_game_week_teams
BEFORE UPDATE ON game_week_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- --Table For Game Weeks 
DROP TABLE IF EXISTS game_weeks CASCADE;

CREATE TABLE game_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER,
    season_year INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_game_weeks
BEFORE UPDATE ON game_weeks
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

CREATE TABLE game_week_matchups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_id INTEGER NOT NULL,
    home_game_week_team_id INTEGER NOT NULL,
    away_game_week_team_id INTEGER NOT NULL,
    home_team_score NUMERIC(8,2) DEFAULT 0.00,
    away_team_score NUMERIC(8,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_game_week_matchups_game_week
        FOREIGN KEY (game_week_id) REFERENCES game_weeks(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_matchups_home_team
        FOREIGN KEY (home_game_week_team_id) REFERENCES game_week_teams(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_matchups_away_team
        FOREIGN KEY (away_game_week_team_id) REFERENCES game_week_teams(id) ON DELETE CASCADE,
    CONSTRAINT unique_gameweek_home_away_team UNIQUE (game_week_id, home_game_week_team_id, away_game_week_team_id),
    CONSTRAINT check_different_teams CHECK (home_game_week_team_id <> away_game_week_team_id)
);

CREATE INDEX index_game_week_matchups_on_game_week_id ON game_week_matchups (game_week_id);
CREATE INDEX index_game_week_matchups_on_home_game_week_team_id ON game_week_matchups (home_game_week_team_id);
CREATE INDEX index_game_week_matchups_on_away_game_week_team_id ON game_week_matchups (away_game_week_team_id);

CREATE TRIGGER set_updated_at_game_week_matchups
BEFORE UPDATE ON game_week_matchups
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- --Table for Match Players 
-- DROP TABLE IF EXISTS match_players CASCADE;

-- CREATE TABLE match_players_original (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     passing_yards INTEGER DEFAULT 0,
--     passing_tds INTEGER DEFAULT 0,
--     passing_twoptm INTEGER DEFAULT 0,
--     rushing_yards INTEGER DEFAULT 0,
--     rushing_tds INTEGER DEFAULT 0,
--     rushing_twoptm INTEGER DEFAULT 0,
--     receiving_yards INTEGER DEFAULT 0,
--     receiving_tds INTEGER DEFAULT 0,
--     receiving_twoptm INTEGER DEFAULT 0,
--     times_sacked INTEGER DEFAULT 0,
--     fumbles_lost INTEGER DEFAULT 0,
--     interceptions_thrown INTEGER DEFAULT 0,
--     field_goals_kicked INTEGER DEFAULT 0,
--     extra_points_kicked INTEGER DEFAULT 0,
--     sacks_made INTEGER DEFAULT 0,
--     defense_touchdowns INTEGER DEFAULT 0,
--     fumbles_won INTEGER DEFAULT 0,
--     interceptions_caught INTEGER DEFAULT 0,
--     points_conceded INTEGER DEFAULT 0,
--     points INTEGER DEFAULT 0,
--     game_week_id INTEGER,
--     nfl_player_id INTEGER,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- CREATE TRIGGER set_updated_at_match_players
-- BEFORE UPDATE ON match_players
-- FOR EACH ROW
-- EXECUTE FUNCTION update_timestamp();

-- ALTER TABLE match_players
-- ADD CONSTRAINT unique_player_gameweek UNIQUE (game_week_id, nfl_player_id);


DROP TABLE IF EXISTS match_players CASCADE; -- WARNING: This will delete the existing table and all its data!
                                          -- Use with extreme caution in production environments.

CREATE TABLE match_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Offensive Passing Statistics
    passing_yards INTEGER DEFAULT 0,
    passing_tds INTEGER DEFAULT 0,
    passing_twoptm INTEGER DEFAULT 0,       -- 2-point conversions (general offensive, or specifically passing)
    interceptions_thrown INTEGER DEFAULT 0,

    -- Offensive Rushing Statistics
    rushing_yards INTEGER DEFAULT 0,
    rushing_tds INTEGER DEFAULT 0,
    rushing_twoptm INTEGER DEFAULT 0,       -- 2-point rushing conversions

    -- Offensive Receiving Statistics
    receiving_receptions INTEGER DEFAULT 0, -- NEW: From NFL_RESULTS.receivingrec
    receiving_yards INTEGER DEFAULT 0,
    receiving_tds INTEGER DEFAULT 0,
    receiving_twoptm INTEGER DEFAULT 0,     -- 2-point receiving conversions

    -- Offensive Misc/Contextual Statistics (from NFL_RESULTS)
    times_sacked INTEGER DEFAULT 0,
    fumbles_lost INTEGER DEFAULT 0,
    touch_carries INTEGER DEFAULT 0,
    touch_receptions INTEGER DEFAULT 0,
    touches INTEGER DEFAULT 0,
    targets_receptions INTEGER DEFAULT 0,
    targets INTEGER DEFAULT 0,
    reception_percentage NUMERIC(5,2) DEFAULT 0.00,
    rz_target INTEGER DEFAULT 0,
    rz_touch INTEGER DEFAULT 0,
    rz_g2g INTEGER DEFAULT 0,

    -- Kicking Statistics (from KICKER_RESULTS)
    pat_made INTEGER DEFAULT 0,             -- NEW: From KICKER_RESULTS.PatMade (extra points made)
    pat_missed INTEGER DEFAULT 0,           -- NEW: From KICKER_RESULTS.PatMissed (extra points missed)
    fg_made_0_19 INTEGER DEFAULT 0,         -- NEW: From KICKER_RESULTS.FgMade_0_19
    fg_made_20_29 INTEGER DEFAULT 0,        -- NEW: From KICKER_RESULTS.FgMade_20_29
    fg_made_30_39 INTEGER DEFAULT 0,        -- NEW: From KICKER_RESULTS.FgMade_30_39
    fg_made_40_49 INTEGER DEFAULT 0,        -- NEW: From KICKER_RESULTS.FgMade_40_49
    fg_made_50_plus INTEGER DEFAULT 0,      -- NEW: From KICKER_RESULTS.FgMade_50 (renamed for clarity)
    fg_miss_0_19 INTEGER DEFAULT 0,         -- NEW: From KICKER_RESULTS.FgMiss_0_19
    fg_miss_20_29 INTEGER DEFAULT 0,        -- NEW: From KICKER_RESULTS.FgMiss_20_29
    fg_miss_30_39 INTEGER DEFAULT 0,        -- NEW: From KICKER_RESULTS.FgMiss_30_39
    -- Note: 'field_goals_kicked' and 'extra_points_kicked' were in original match_players.
    -- They can be *derived* from the new granular fields during scoring or insertion.
    -- Keeping them for direct calculation based on the prior design for now, but
    -- 'field_goals_kicked' would be SUM(fg_made_x_y). 'extra_points_kicked' would be pat_made.
    -- Let's keep them and clarify their source during insert.

    -- Defensive Statistics (from NFL_DEFENSIVE_RESULTS)
    tackles_total INTEGER DEFAULT 0,        -- NEW: From TacklesTot
    tackles_assisted INTEGER DEFAULT 0,     -- NEW: From TacklesAst
    sacks_made NUMERIC(8,2) DEFAULT 0.00,   -- MODIFIED: From INTEGER to NUMERIC(8,2) to match TacklesSck
    tackles_for_loss INTEGER DEFAULT 0,     -- NEW: From TacklesTfl
    forced_fumbles INTEGER DEFAULT 0,       -- NEW: From TurnoverFrcFum
    fumbles_won INTEGER DEFAULT 0,          -- Matches TurnoverFumRec
    interceptions_caught INTEGER DEFAULT 0, -- Matches TurnoverInt
    safeties INTEGER DEFAULT 0,             -- NEW: From ScoreSaf
    defensive_two_pt_returns INTEGER DEFAULT 0, -- NEW: From ScoreDef2ptRet
    blocked_kicks INTEGER DEFAULT 0,        -- NEW: From Blk (ScoreBlkTd implies TD from block)
    passes_defended INTEGER DEFAULT 0,      -- NEW: From PDef
    qb_hits INTEGER DEFAULT 0,              -- NEW: From QBHit
    interception_return_yards INTEGER DEFAULT 0, -- NEW: From ReturnIntYds
    fumble_return_yards INTEGER DEFAULT 0,  -- NEW: From ReturnFumYds
    defense_touchdowns INTEGER DEFAULT 0,   -- Consolidated from ScoreIntTd, ScoreFumTd, ScoreBlkTd

    -- General/Derived Metrics
    points_conceded NUMERIC(8,2) DEFAULT 0.00, -- MODIFIED: From INTEGER to NUMERIC(8,2)
    points NUMERIC(8,2) DEFAULT 0.00,          -- MODIFIED: From INTEGER to NUMERIC(8,2)

    game_week_id INTEGER,
    nfl_player_id INTEGER,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Composite Unique Constraint
    CONSTRAINT unique_player_gameweek UNIQUE (game_week_id, nfl_player_id)
);


-- Table for NFL Player Types
DROP TABLE IF EXISTS nfl_player_types CASCADE;


-- Table for NFL PLayers 
DROP TABLE IF EXISTS nfl_players CASCADE;

CREATE TABLE nfl_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    nfl_id VARCHAR(255), -- Assuming nfl_id is a string identifier
    nfl_team_id INTEGER,
    position_type VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_players
BEFORE UPDATE ON nfl_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

--Table for NFL Teams 
DROP TABLE IF EXISTS nfl_teams CASCADE;

CREATE TABLE nfl_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_teams
BEFORE UPDATE ON nfl_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for Leagues
DROP TABLE IF EXISTS leagues CASCADE;

CREATE TABLE leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    commissioner_user_id INTEGER, -- Optional: to denote who created/manages the league
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- Table for Users
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    team_name VARCHAR(255),
    password_hash VARCHAR(255), -- Storing hash and salt as strings
    password_salt VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


CREATE TRIGGER set_updated_at_leagues
BEFORE UPDATE ON leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for User-League Relationships (many-to-many)
DROP TABLE IF EXISTS user_leagues CASCADE;

CREATE TABLE user_leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    league_id INTEGER NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Optional: role within the league (e.g., 'member', 'admin')
    role VARCHAR(255) DEFAULT 'member',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_user_league UNIQUE (user_id, league_id),
    CONSTRAINT fk_user_leagues_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_leagues_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_leagues
BEFORE UPDATE ON user_leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for User_roster
DROP TABLE IF EXISTS user_roster CASCADE;

CREATE TABLE user_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    nfl_player_id INTEGER NOT NULL,
    team_name VARCHAR(255), -- Team name for the roster
    season_year INTEGER NOT NULL, -- Year of the season
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_user_roster
BEFORE UPDATE ON user_roster
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

DROP TABLE IF EXISTS modes CASCADE;

CREATE TABLE modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL, -- Name of the scoring mode (e.g., 'ESPN', 'Yahoo', 'Standard')

    -- Offensive Multipliers
    passing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_thrown_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receptions_multiplier NUMERIC(5,2) DEFAULT 0.00, -- NEW: For PPR scoring
    two_pt_conversion_multiplier NUMERIC(5,2) DEFAULT 0.00, -- Consolidated 2-pt conversions
    fumbles_lost_multiplier NUMERIC(5,2) DEFAULT 0.00,
    times_sacked_multiplier NUMERIC(5,2) DEFAULT 0.00,

    -- Kicking Multipliers (Granular Field Goals & XP Misses)
    extra_points_kicked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_missed_multiplier NUMERIC(5,2) DEFAULT 0.00, -- NEW
    fg_made_0_19_multiplier NUMERIC(5,2) DEFAULT 0.00,      -- NEW
    fg_made_20_29_multiplier NUMERIC(5,2) DEFAULT 0.00,      -- NEW
    fg_made_30_39_multiplier NUMERIC(5,2) DEFAULT 0.00,      -- NEW
    fg_made_40_49_multiplier NUMERIC(5,2) DEFAULT 0.00,      -- NEW
    fg_made_50_plus_multiplier NUMERIC(5,2) DEFAULT 0.00,    -- NEW
    -- Note: fg_miss_X_Y_multiplier columns can be added here if you want to differentiate miss penalties by distance
    -- For now, relying on sum of `fg_made_` for total FGs and default values for misses.

    -- Defensive/Special Teams Multipliers (for individual defensive players or team D/ST)
    sacks_made_multiplier NUMERIC(5,2) DEFAULT 0.00,        -- Used for D/ST or IDP
    defense_touchdowns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_won_multiplier NUMERIC(5,2) DEFAULT 0.00,       -- General fumble recoveries
    interceptions_caught_multiplier NUMERIC(5,2) DEFAULT 0.00, -- General interceptions

    -- NEW: Granular Defensive Stats
    tackles_total_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_assisted_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_for_loss_multiplier NUMERIC(5,2) DEFAULT 0.00,
    forced_fumbles_multiplier NUMERIC(5,2) DEFAULT 0.00,
    safeties_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defensive_two_pt_returns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    blocked_kicks_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passes_defended_multiplier NUMERIC(5,2) DEFAULT 0.00,
    qb_hits_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interception_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumble_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add a trigger for updated_at (ensure the update_timestamp() function exists from previous steps)
CREATE TRIGGER set_updated_at_modes
BEFORE UPDATE ON modes
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for League Settings
DROP TABLE IF EXISTS league_settings CASCADE;

CREATE TABLE league_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id INTEGER UNIQUE NOT NULL, -- Each league has one set of settings
    
    -- General Roster Settings
    total_roster_size INTEGER NOT NULL DEFAULT 16, -- Max players a team can have
    starting_lineup_size INTEGER NOT NULL DEFAULT 9, -- Number of players required in starting lineup
    bench_size INTEGER NOT NULL DEFAULT 7, -- Number of players on the bench

    -- Position Bucket Requirements (JSONB for flexibility)
    -- Example: {"QB": 1, "RB": 2, "WR": 2, "TE": 1, "FLEX": 1, "K": 1, "DEF": 1}
    starting_position_requirements JSONB NOT NULL DEFAULT '{}'::jsonb, 

    -- Scoring Mode (Reference to 'modes' table)
    mode_id INTEGER NOT NULL DEFAULT 1, -- Default to a standard mode, e.g., ID 1

    -- Draft Settings (assuming a snake draft for now)
    draft_type VARCHAR(255) NOT NULL DEFAULT 'Snake', -- 'Snake', 'Auction', 'Manual'
    draft_order_reversed_after_round BOOLEAN NOT NULL DEFAULT TRUE, -- For Snake draft
    picks_per_round INTEGER NOT NULL DEFAULT 1, -- Typically 1
    draft_start_date TIMESTAMP WITH TIME ZONE, -- When the draft officially opens
    draft_end_date TIMESTAMP WITH TIME ZONE,   -- When the draft officially closes

    -- Waiver Settings
    waiver_type VARCHAR(255) NOT NULL DEFAULT 'FAAB', -- 'FAAB', 'WaiverOrder', 'FirstComeFirstServe'
    faab_budget INTEGER NOT NULL DEFAULT 100, -- For FAAB waivers
    waiver_run_day VARCHAR(255) DEFAULT 'Wednesday', -- e.g., 'Wednesday', 'Tuesday'
    waiver_run_time TIME WITH TIME ZONE DEFAULT '03:00:00-07', -- e.g., 3:00 AM PST

    -- Trade Settings
    allow_trades BOOLEAN NOT NULL DEFAULT TRUE,
    trade_deadline TIMESTAMP WITH TIME ZONE,
    trade_review_period_hours INTEGER DEFAULT 24, -- Hours for league review before trade processes

    -- Playoff Settings
    playoff_start_week INTEGER, -- The game_week.number when playoffs begin
    num_playoff_teams INTEGER,
    championship_week INTEGER, -- The game_week.number for the championship game

    -- League State/Status
    league_status VARCHAR(255) NOT NULL DEFAULT 'Drafting', -- 'Pre-Draft', 'Drafting', 'Regular Season', 'Playoffs', 'Completed'

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Foreign Key Constraint
    CONSTRAINT fk_league_settings_league
        FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_league_settings_mode
        FOREIGN KEY (mode_id) REFERENCES modes(id) ON DELETE RESTRICT -- Don't delete a mode if leagues use it
);

CREATE INDEX index_league_settings_on_league_id ON league_settings (league_id);
CREATE INDEX index_league_settings_on_mode_id ON league_settings (mode_id);

CREATE TRIGGER set_updated_at_league_settings
BEFORE UPDATE ON league_settings
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();