-- Create necessary extensions if they don't exist (for UUID generation)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Function to update the 'updated_at' column
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- --- PUBLIC SCHEMA TABLES ---

-- Table for Users (Updated to link with Supabase Auth UUID)
DROP TABLE IF EXISTS fantasy.users CASCADE;

CREATE TABLE fantasy.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- This column stores the UUID from Supabase's auth.users table
    auth_user_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(), -- Use gen_random_uuid() as a default for new inserts, but typically set by app from auth.uid()
    name VARCHAR(255),
    team_name VARCHAR(255),
    team_description TEXT,
    -- password_hash and password_salt are handled by Supabase Auth (auth.users table)
    -- Remove these from your fantasy.users table unless you're managing your own auth
    -- password_hash VARCHAR(255),
    -- password_salt VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_users
BEFORE UPDATE ON fantasy.users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Leagues (No change needed from your provided schema, assuming commissioner_user_id links to fantasy.users.id)
DROP TABLE IF EXISTS fantasy.leagues CASCADE;

CREATE TABLE fantasy.leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    commissioner_user_id INTEGER REFERENCES fantasy.users(id) ON DELETE SET NULL, -- Optional: to denote who created/manages the league, links to fantasy.users.id
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_leagues
BEFORE UPDATE ON fantasy.leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for User-League Relationships (many-to-many) (Updated to use auth_user_id)
DROP TABLE IF EXISTS fantasy.user_leagues CASCADE;

CREATE TABLE fantasy.user_leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NOT NULL, -- Changed from user_id INTEGER
    league_id INTEGER NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    role VARCHAR(255) DEFAULT 'member',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_user_league UNIQUE (auth_user_id, league_id), -- Constraint updated
    CONSTRAINT fk_user_leagues_user FOREIGN KEY (auth_user_id) REFERENCES fantasy.users(auth_user_id) ON DELETE CASCADE, -- FK updated
    CONSTRAINT fk_user_leagues_league FOREIGN KEY (league_id) REFERENCES fantasy.leagues(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_leagues
BEFORE UPDATE ON fantasy.user_leagues
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for User Roster (Updated to use auth_user_id)
DROP TABLE IF EXISTS fantasy.user_roster CASCADE;

CREATE TABLE fantasy.user_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_auth_id UUID NOT NULL, -- Changed from user_id INTEGER
    nfl_player_id INTEGER NOT NULL,
    team_name VARCHAR(255),
    season_year INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_user_roster_user FOREIGN KEY (user_auth_id) REFERENCES fantasy.users(auth_user_id) ON DELETE CASCADE -- FK updated
);

CREATE TRIGGER set_updated_at_user_roster
BEFORE UPDATE ON fantasy.user_roster
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Teams (Updated to use auth_user_id)
DROP TABLE IF EXISTS fantasy.game_week_teams CASCADE;

CREATE TABLE fantasy.game_week_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_auth_id UUID, -- Changed from user_id INTEGER
    league_id INTEGER NOT NULL DEFAULT 1,
    game_week_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_game_week_teams_league FOREIGN KEY (league_id) REFERENCES fantasy.leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_teams_user FOREIGN KEY (user_auth_id) REFERENCES fantasy.users(auth_user_id) ON DELETE SET NULL -- FK updated
);

-- Add an index for league_id on game_week_teams for better query performance
CREATE INDEX index_game_week_teams_on_league_id ON fantasy.game_week_teams (league_id);
CREATE INDEX index_game_week_teams_on_user_auth_id ON fantasy.game_week_teams (user_auth_id); -- Index updated

CREATE TRIGGER set_updated_at_game_week_teams
BEFORE UPDATE ON fantasy.game_week_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Team Players (No change needed, references game_week_team_id which is okay)
DROP TABLE IF EXISTS fantasy.game_week_team_players CASCADE;

CREATE TABLE fantasy.game_week_team_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_team_id INTEGER REFERENCES fantasy.game_week_teams(id) ON DELETE CASCADE,
    nfl_player_id INTEGER,
    playing BOOLEAN,
    roster_slot VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_player_gameweek_team UNIQUE (game_week_team_id, nfl_player_id)
);

CREATE INDEX index_game_week_team_players_on_game_week_team_id ON fantasy.game_week_team_players (game_week_team_id);
CREATE INDEX index_game_week_team_players_on_nfl_player_id ON fantasy.game_week_team_players (nfl_player_id);

CREATE TRIGGER set_updated_at_game_week_team_players
BEFORE UPDATE ON fantasy.game_week_team_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table For Game Weeks (No change needed)
DROP TABLE IF EXISTS fantasy.game_weeks CASCADE;

CREATE TABLE fantasy.game_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER,
    season_year INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_game_weeks
BEFORE UPDATE ON fantasy.game_weeks
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Game Week Matchups (No change needed, references game_week_teams.id)
DROP TABLE IF EXISTS fantasy.game_week_matchups CASCADE;

CREATE TABLE fantasy.game_week_matchups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_week_id INTEGER NOT NULL,
    home_game_week_team_id INTEGER NOT NULL,
    away_game_week_team_id INTEGER NOT NULL,
    home_team_score NUMERIC(8,2) DEFAULT 0.00,
    away_team_score NUMERIC(8,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_game_week_matchups_game_week
        FOREIGN KEY (game_week_id) REFERENCES fantasy.game_weeks(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_matchups_home_team
        FOREIGN KEY (home_game_week_team_id) REFERENCES fantasy.game_week_teams(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_week_matchups_away_team
        FOREIGN KEY (away_game_week_team_id) REFERENCES fantasy.game_week_teams(id) ON DELETE CASCADE,
    CONSTRAINT unique_gameweek_home_away_team UNIQUE (game_week_id, home_game_week_team_id, away_game_week_team_id),
    CONSTRAINT check_different_teams CHECK (home_game_week_team_id <> away_game_week_team_id)
);

CREATE INDEX index_game_week_matchups_on_game_week_id ON fantasy.game_week_matchups (game_week_id);
CREATE INDEX index_game_week_matchups_on_home_game_week_team_id ON fantasy.game_week_matchups (home_game_week_team_id);
CREATE INDEX index_game_week_matchups_on_away_game_week_team_id ON fantasy.game_week_matchups (away_game_week_team_id);

CREATE TRIGGER set_updated_at_game_week_matchups
BEFORE UPDATE ON fantasy.game_week_matchups
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Match Players (No change needed, references game_week_id and nfl_player_id)
DROP TABLE IF EXISTS fantasy.match_players CASCADE;

CREATE TABLE fantasy.match_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Offensive Passing Statistics
    passing_yards INTEGER DEFAULT 0,
    passing_tds INTEGER DEFAULT 0,
    passing_twoptm INTEGER DEFAULT 0,
    interceptions_thrown INTEGER DEFAULT 0,
    -- Offensive Rushing Statistics
    rushing_yards INTEGER DEFAULT 0,
    rushing_tds INTEGER DEFAULT 0,
    rushing_twoptm INTEGER DEFAULT 0,
    -- Offensive Receiving Statistics
    receiving_receptions INTEGER DEFAULT 0,
    receiving_yards INTEGER DEFAULT 0,
    receiving_tds INTEGER DEFAULT 0,
    receiving_twoptm INTEGER DEFAULT 0,
    -- Offensive Misc/Contextual Statistics (from NFL_RESULTS)
    times_sacked INTEGER DEFAULT 0,
    fumbles_lost INTEGER DEFAULT 0,
    touch_carries INTEGER DEFAULT 0,
    touch_receptions INTEGER DEFAULT 0,
    touches INTEGER DEFAULT 0,
    targets_receptions INTEGER DEFAULT 0,
    targets INTEGER DEFAULT 0,
    reception_percentage NUMERIC(5,2) DEFAULT 0.00,
    rz_target INTEGER DEFAULT 0,
    rz_touch INTEGER DEFAULT 0,
    rz_g2g INTEGER DEFAULT 0,
    -- Kicking Statistics (from KICKER_RESULTS)
    pat_made INTEGER DEFAULT 0,
    pat_missed INTEGER DEFAULT 0,
    fg_made_0_19 INTEGER DEFAULT 0,
    fg_made_20_29 INTEGER DEFAULT 0,
    fg_made_30_39 INTEGER DEFAULT 0,
    fg_made_40_49 INTEGER DEFAULT 0,
    fg_made_50_plus INTEGER DEFAULT 0,
    fg_miss_0_19 INTEGER DEFAULT 0,
    fg_miss_20_29 INTEGER DEFAULT 0,
    fg_miss_30_39 INTEGER DEFAULT 0,
    -- Defensive Statistics (from NFL_DEFENSIVE_RESULTS)
    tackles_total INTEGER DEFAULT 0,
    tackles_assisted INTEGER DEFAULT 0,
    sacks_made NUMERIC(8,2) DEFAULT 0.00,
    tackles_for_loss INTEGER DEFAULT 0,
    forced_fumbles INTEGER DEFAULT 0,
    fumbles_won INTEGER DEFAULT 0,
    interceptions_caught INTEGER DEFAULT 0,
    safeties INTEGER DEFAULT 0,
    defensive_two_pt_returns INTEGER DEFAULT 0,
    blocked_kicks INTEGER DEFAULT 0,
    passes_defended INTEGER DEFAULT 0,
    qb_hits INTEGER DEFAULT 0,
    interception_return_yards INTEGER DEFAULT 0,
    fumble_return_yards INTEGER DEFAULT 0,
    defense_touchdowns INTEGER DEFAULT 0,
    -- General/Derived Metrics
    points_conceded NUMERIC(8,2) DEFAULT 0.00,
    points NUMERIC(8,2) DEFAULT 0.00,
    game_week_id INTEGER,
    nfl_player_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_player_gameweek UNIQUE (game_week_id, nfl_player_id)
);


-- Table for NFL Player Types (No change needed)
DROP TABLE IF EXISTS fantasy.nfl_player_types CASCADE;
-- Define columns for nfl_player_types if this table is actually used.
-- Example: CREATE TABLE fantasy.nfl_player_types (id SERIAL PRIMARY KEY, type_name VARCHAR(255) UNIQUE);


-- Table for NFL Players (No change needed)
DROP TABLE IF EXISTS fantasy.nfl_players CASCADE;

CREATE TABLE fantasy.nfl_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    nfl_id VARCHAR(255),
    nfl_team_id INTEGER REFERENCES fantasy.nfl_teams(id) ON DELETE SET NULL, -- Added FK
    position_type VARCHAR(255), -- Could reference nfl_player_types.type_name if defined
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_players
BEFORE UPDATE ON fantasy.nfl_players
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for NFL Teams (No change needed)
DROP TABLE IF EXISTS fantasy.nfl_teams CASCADE;

CREATE TABLE fantasy.nfl_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_nfl_teams
BEFORE UPDATE ON fantasy.nfl_teams
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for Modes (No change needed)
DROP TABLE IF EXISTS fantasy.modes CASCADE;

CREATE TABLE fantasy.modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    passing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_thrown_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    rushing_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receiving_tds_multiplier NUMERIC(5,2) DEFAULT 0.00,
    receptions_multiplier NUMERIC(5,2) DEFAULT 0.00,
    two_pt_conversion_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_lost_multiplier NUMERIC(5,2) DEFAULT 0.00,
    times_sacked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_kicked_multiplier NUMERIC(5,2) DEFAULT 0.00,
    extra_points_missed_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_0_19_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_20_29_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_30_39_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_40_49_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fg_made_50_plus_multiplier NUMERIC(5,2) DEFAULT 0.00,
    sacks_made_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defense_touchdowns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumbles_won_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interceptions_caught_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_total_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_assisted_multiplier NUMERIC(5,2) DEFAULT 0.00,
    tackles_for_loss_multiplier NUMERIC(5,2) DEFAULT 0.00,
    forced_fumbles_multiplier NUMERIC(5,2) DEFAULT 0.00,
    safeties_multiplier NUMERIC(5,2) DEFAULT 0.00,
    defensive_two_pt_returns_multiplier NUMERIC(5,2) DEFAULT 0.00,
    blocked_kicks_multiplier NUMERIC(5,2) DEFAULT 0.00,
    passes_defended_multiplier NUMERIC(5,2) DEFAULT 0.00,
    qb_hits_multiplier NUMERIC(5,2) DEFAULT 0.00,
    interception_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    fumble_return_yards_multiplier NUMERIC(5,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_modes
BEFORE UPDATE ON fantasy.modes
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- Table for League Settings (No change needed)
DROP TABLE IF EXISTS fantasy.league_settings CASCADE;

CREATE TABLE fantasy.league_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id INTEGER UNIQUE NOT NULL,
    total_roster_size INTEGER NOT NULL DEFAULT 16,
    starting_lineup_size INTEGER NOT NULL DEFAULT 9,
    bench_size INTEGER NOT NULL DEFAULT 7,
    starting_position_requirements JSONB NOT NULL DEFAULT '{}'::jsonb,
    mode_id INTEGER NOT NULL DEFAULT 1,
    draft_type VARCHAR(255) NOT NULL DEFAULT 'Snake',
    draft_order_reversed_after_round BOOLEAN NOT NULL DEFAULT TRUE,
    picks_per_round INTEGER NOT NULL DEFAULT 1,
    draft_start_date TIMESTAMP WITH TIME ZONE,
    draft_end_date TIMESTAMP WITH TIME ZONE,
    waiver_type VARCHAR(255) NOT NULL DEFAULT 'FAAB',
    faab_budget INTEGER NOT NULL DEFAULT 100,
    waiver_run_day VARCHAR(255) DEFAULT 'Wednesday',
    waiver_run_time TIME WITH TIME ZONE DEFAULT '03:00:00-07',
    allow_trades BOOLEAN NOT NULL DEFAULT TRUE,
    trade_deadline TIMESTAMP WITH TIME ZONE,
    trade_review_period_hours INTEGER DEFAULT 24,
    playoff_start_week INTEGER,
    num_playoff_teams INTEGER,
    championship_week INTEGER,
    league_status VARCHAR(255) NOT NULL DEFAULT 'Drafting',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_league_settings_league
        FOREIGN KEY (league_id) REFERENCES fantasy.leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_league_settings_mode
        FOREIGN KEY (mode_id) REFERENCES fantasy.modes(id) ON DELETE RESTRICT
);

CREATE INDEX index_league_settings_on_league_id ON fantasy.league_settings (league_id);
CREATE INDEX index_league_settings_on_mode_id ON fantasy.league_settings (mode_id);

CREATE TRIGGER set_updated_at_league_settings
BEFORE UPDATE ON fantasy.league_settings
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


-- --- REALTIME SCHEMA TABLES ---

-- Create the realtime schema
CREATE SCHEMA IF NOT EXISTS realtime;

-- Table for Realtime Topics
DROP TABLE IF EXISTS realtime.topics CASCADE;

CREATE TABLE realtime.topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    league_id INTEGER REFERENCES fantasy.leagues(id) ON DELETE CASCADE, -- Link to a specific league, can be NULL for global topics
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_realtime_topics
BEFORE UPDATE ON realtime.topics
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Table for Realtime Messages
DROP TABLE IF EXISTS realtime.messages CASCADE;

CREATE TABLE realtime.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(255) NOT NULL REFERENCES realtime.topics(name) ON UPDATE CASCADE, -- FK to realtime.topics.name
    sender_auth_id UUID NOT NULL REFERENCES fantasy.users(auth_user_id) ON DELETE CASCADE, -- Link to the Supabase auth.users UUID
    content TEXT NOT NULL,
    extension VARCHAR(255) DEFAULT 'message', -- e.g., 'message', 'broadcast', 'system'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_realtime_messages
BEFORE UPDATE ON realtime.messages
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();